// frontend/vue/src/components/AppSwitcher.vue
<template>
  <select class="app-switcher" :value="currentId" @change="handleChange">
    <option v-for="a in apps" :key="a.id" :value="a.id">{{ a.name }}</option>
  </select>
</template>

<script setup>
import appsConfig from '../../../apps.config.json'

const apps = appsConfig.apps

const currentId = apps.find(
  (a) => a.url === `${location.protocol}//${location.host}`
)?.id ?? 'vue'

function handleChange(e) {
  const app = apps.find((a) => a.id === e.target.value)
  if (app) window.location.href = app.url
}
</script>

// frontend/react/src/components/AppSwitcher.jsx
import React from 'react'
import appsConfig from '../../../apps.config.json'

export default function AppSwitcher() {
  const currentId = appsConfig.apps.find(
    (a) => a.url === `${location.protocol}//${location.host}`
  )?.id ?? 'react'

  function handleChange(e) {
    const app = appsConfig.apps.find((a) => a.id === e.target.value)
    if (app) window.location.href = app.url
  }

  return (
    <select className="app-switcher" value={currentId} onChange={handleChange}>
      {appsConfig.apps.map((a) => (
        <option key={a.id} value={a.id}>{a.name}</option>
      ))}
    </select>
  )
}
