// frontend/vue/src/components/BackendSwitcher.vue
<template>
  <select class="backend-switcher" :value="currentId" @change="handleChange">
    <option v-for="b in backends" :key="b.id" :value="b.id">{{ b.name }}</option>
  </select>
</template>

<script setup>
import appsConfig from '../../../apps.config.json'
import { getBackendUrl, setBackendUrl } from '../api/wilayah'

const backends = appsConfig.backends
const currentUrl = getBackendUrl()
const currentId = backends.find((b) => b.url === currentUrl)?.id ?? backends[0].id

function handleChange(e) {
  const backend = backends.find((b) => b.id === e.target.value)
  if (backend) {
    setBackendUrl(backend.url)
    window.location.reload()
  }
}
</script>

// frontend/react/src/components/BackendSwitcher.jsx
import React from 'react'
import appsConfig from '../../../apps.config.json'
import { getBackendUrl, setBackendUrl } from '../api/wilayah'

export default function BackendSwitcher() {
  const currentUrl = getBackendUrl()
  const currentId = appsConfig.backends.find((b) => b.url === currentUrl)?.id
    ?? appsConfig.backends[0].id

  function handleChange(e) {
    const backend = appsConfig.backends.find((b) => b.id === e.target.value)
    if (backend) {
      setBackendUrl(backend.url)
      window.location.reload()
    }
  }

  return (
    <select className="backend-switcher" value={currentId} onChange={handleChange}>
      {appsConfig.backends.map((b) => (
        <option key={b.id} value={b.id}>{b.name}</option>
      ))}
    </select>
  )
}
