// frontend/vue/src/components/WilayahSelect.vue
<template>
  <div class="select-group">
    <label>{{ label }}</label>
    <select :value="modelValue" @change="$emit('update:modelValue', $event.target.value)" :disabled="disabled">
      <option value="">{{ placeholder }}</option>
      <option v-for="item in options" :key="item.kode" :value="item.kode">
        {{ item.nama }}
      </option>
    </select>
  </div>
</template>

<script setup>
defineProps({
  label: String,
  placeholder: String,
  options: { type: Array, default: () => [] },
  modelValue: String,
  disabled: Boolean,
})
defineEmits(['update:modelValue'])
</script>

// frontend/react/src/components/WilayahSelect.jsx
import React from 'react'

export default function WilayahSelect({ label, placeholder, options, value, onChange, disabled }) {
  return (
    <div className="select-group">
      <label>{label}</label>
      <select value={value} onChange={(e) => onChange(e.target.value)} disabled={disabled}>
        <option value="">{placeholder}</option>
        {options.map((item) => (
          <option key={item.kode} value={item.kode}>
            {item.nama}
          </option>
        ))}
      </select>
    </div>
  )
}
